// <auto-generated />
using System;
using PressINK_Server_App.Data.API_Forms;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PressINK_Server_App.Migrations
{
    [DbContext(typeof(API_FormContext))]
    [Migration("20260211140705_adding_modes")]
    partial class adding_modes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AAP_PRINT_Dashboard.Model.API_Form_Models.API_Template_Attributes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("API_TemplatesID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Attribute_Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Attribute_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Attribute_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("API_TemplatesID");

                    b.ToTable("API_Template_Attributes");
                });

            modelBuilder.Entity("AAP_PRINT_Dashboard.Model.API_Form_Models.API_Templates", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Attribute_Search_Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Template_Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Template_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("API_Templates");
                });

            modelBuilder.Entity("AAP_PRINT_Dashboard.Model.API_Form_Models.Attribute_Type", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Attribute_Type");
                });

            modelBuilder.Entity("AAP_PRINT_Dashboard.Model.API_Form_Models.Model_Attributes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Attribute_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Attribute_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Attribute_Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Model_ID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Model_Attributes");
                });

            modelBuilder.Entity("AAP_PRINT_Dashboard.Model.API_Form_Models.API_Template_Attributes", b =>
                {
                    b.HasOne("AAP_PRINT_Dashboard.Model.API_Form_Models.API_Templates", "API_Templates")
                        .WithMany("Attributes")
                        .HasForeignKey("API_TemplatesID");

                    b.Navigation("API_Templates");
                });

            modelBuilder.Entity("AAP_PRINT_Dashboard.Model.API_Form_Models.API_Templates", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
